defaults: &defaults
  docker:
    - image: circleci/node:10.16.3
  working_directory: ~/app
version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/app
      - run: 'sudo npm install -g npm@5'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: npm test
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_test_results:
          path: test-results.xml
      - persist_to_workspace:
          root: .
          paths: .
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run: sudo npm install -g now axios execa
      - run: npm link now
      - run: npm link axios
      - run: npm link execa
      - deploy:
          name: Deploy
          command: bin/deploy
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
